<?php
$fortunes = array(
  array(
'Jsem kernel panic, neni to lehky nesel bych za nic do naky /dev/ky...'."\n".
'							--Kevin'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Tuxuv_anal/2008/7/linuxove-ctyrversi/diskuse#36'),
  array('Tss, z MŠ mě pustili vo rok dřív, jak sem byl chytrej :P Už jsem uměl napsat PIVO i se'."\n".
'zavázanýma očima.'."\n".
'							--Darm'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Saljack/2010/4/mala-pomoc-s-javou#43'),
  array('Reakce na kalhotky C-String: Je to výbornej nápad,'."\n".
'vohnul sem si naběračku na polívku, sklapnul půlky a teď tady v tom běhám po bytě...'."\n".
'							--Amigapower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/puppylinux/2010/9/cstring#1'),
  array('Tím šťastlivcem se stal soutěžící kotyz, který s odpovědí přispěchal jen několik minut'."\n".
'po vyhlášení soutěže a dostane tedy téměř dvoumetrové plátno s leteckým snímkem centra'."\n".
'Sydney s rozlišením 8 541 x 4 357 pixelů.'."\n".
'							--zive.cz'."\n".
''."\n".
'', 'http://www.zive.cz/bleskovky/vysledky-souteze-o-obrovsky-snimek-z-google-earth/sc-4-a-148305/default.aspx'),
  array('Ty mi děláš torčr!'."\n".
'							--vlastikroot'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/HF/2010/7/reportaz-z-masters-of-rock'),
  array('...konzole pyčo, na tom se věšej záclony... :-D'."\n".
'							--Amigapower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/TryCatch/2010/2/jak-jsem-hledal-vyhovujici-terminal-pro-windows#55'),
  array('Sorry, ale když "danajský dar" vypadne z Amigapowera, "nenormální přeumělkovaná řeč" asi'."\n".
'není na místě.'."\n".
'							--Archer'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/merlins/2010/10/statni-maturita/diskuse#67'),
  array('Svoboda zůstává obrovskou překážkou pro růst moci.'."\n".
'							--kralyk'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/yet_another_blog/2010/1/hudebni-prumysl-nas-bavi/diskuse#2'),
  array('Jardík: Mně to přijde trhaný'."\n".
'vlastikroot: Laguje ti mozek'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Standovo/2009/10/windows-7-prvni-zklamani/diskuse#146'),
  array('AsciiWolf: Chtělo by to upravit engine ábíčka tak, aby byl u blogů tag break vložen'."\n".
'automaticky - před první obrázek, delší odstavec, atd...'."\n".
'Amigapower: A aby ti to přineslo pivo k televizi nechceš?'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/txt/2010/10/zacala-tu-smrdet-mirna-cenzura-blogu.-koncim.-odchazim#43'),
  array('belisarivs: A to mas jako dva holici strojky, jeden na vercajk a druhy na hubu?'."\n".
'Amigapower: Přece si nebudu holit ptáka stejnym, víš kolik je na xichtu bakterií?!'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2010/8/holite-si-pindoura#10'),
  array('Grunt: Ty máš řidičák? Který blázen?'."\n".
'Amigapower: To sis myslel, že jsem najezdil 300 000 km bez papírů?'."\n".
'SPM: Auto jezdí na benzin, ne na papíry ;)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/zabruceni/2010/12/gong-fu-cha/diskuse#72'),
  array('gtz: a co Comix s nějakou kočkou'."\n".
'Amigapower: V hlavě už je Comix s Marcelkou, bude mít děj se zápletkou ;-)'."\n".
'kotyz: a bude dostatecne oplzlej?'."\n".
'Amigapower: ...ty budeš Jaba'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2010/12/comix-kernel-ultras-0002/diskuse#16'),
  array('Politika a zločin k sobě neodlučitelně patří ... asi jako zubaři a The Coca-Cola Company'."\n".
'							--kralyk'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/ankety/radio#83'),
  array('Příští semestr si zapíšu předmět Administrace Windows jen proto, abych tam mohl přijít v'."\n".
'triku KU.'."\n".
'							--kralyk'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2010/10/hleda-se-kernel-ultras-logistic-manager/diskuse#10'),
  array('Po F# vyvinou G♭, ale zjistí, že vyvinuli úplně to stejné...'."\n".
'							--kralyk'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/f-2.0-uvolnen-pod-open-source-licenci/diskuse#13'),
  array('Vždycky se najde eskymák, který vydá směrnici pro obyvatele rovníkové Afriky,'."\n".
'jak se mají chovat v případě vlny neobvyklých veder.'."\n".
'							--Dalibor Smolík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Mig_Alley/2010/10/kuba-zehli-7-kotev/diskuse#51'),
  array('Asi stárnu, ale pro mě je odpočinek také procházka se psem. Ten nikdy nezklame. Zejména,'."\n".
'když je krásně a člověk se může dívat na krásy přírody, zejména pokud mají minisukně. :-)'."\n".
'							--Dalibor Smolík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2010/11/osude-mam-z-tebe-strach/diskuse#58'),
  array('Marcelka je prostě docela dobrá samička, jenže s pavučinou přes lízátko, někde si to'."\n".
'vybít holt musí...'."\n".
'							--Amigapower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Strider_BSD_koutek/2010/10/svoboda-pro-vsechny/diskuse#167'),
  array('Profil - kokot'."\n".
'Pokud jste kokot, přihlaste se a bude vám zobrazena vaše domovská stránka'."\n".
'							--AsciiWolf'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Mostly_IMDB/2010/10/sedm-kotev-aneb-jak-se-v-sedmi-krocich-zesmesnit/diskuse#223'),
  array('Asimetrický. Asi metr vysoký, asi metr široký :-)'."\n".
'							--Dalibor Smolík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/kotyzblog/2010/12/alkehol-ultras-comix-remix-by-kotyz#20'),
  array('ty vole! až do 21.12.2012 jen čínský polivky'."\n".
'							--Amigapower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2011/2/dekujete-odchazite-tahnete-a-uz-se-nevracejte/diskuse#180'),
  array('kotyz: je 17:30 dostatecne mimo misu? :-D'."\n".
'kralyk: 17:30 obvykle bejvá míň mimo mísu než 14:00...'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Untitled/2010/11/viceznacne-zasifrovani-a-autorsky-zakon/diskuse#21'),
  array('qiRzT: Převést peníze na životy ještě nějak jde, ale opačně už to moc nejde. Jakou má'."\n".
'cenu život dítěte?'."\n".
'Dalibor Smolík: Když se narodí, má tak kolem 3,5 kg. Je to i s kostí, takže za to moc peněz'."\n".
'nebude :)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/pyx/2010/10/zrudy/diskuse#436'),
  array('Ty asi budeš retartovaný jako většina místní verbeže.'."\n".
'							--Petr Tomeš'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/ptomes/2008/3/firefox-3-je-nejrychlejsi-ve-zpracovani-javascriptu/diskuse#215'),
  array('Mozilla dělá program pro 300 milionů lidí, díky kterýmu pokračují inovace na webu a'."\n".
'vyvíjí se i dominantní prohlížeč.'."\n".
'							--Petr Tomeš'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/firefox-3.5-rc/diskuse#150'),
  array('Opera dělá vcelku bezvýznamný produkt vesměs pro pár procent méně náročných úchyláků,'."\n".
'kteří se spokojí s omezenými možnostmi Opery a jejími vyššími paměťovými nároky.'."\n".
'							--Petr Tomeš'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/firefox-3.5-rc/diskuse#150'),
  array('Proč lžeš?'."\n".
'							--Petr Tomeš'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/firefox-4-mame-se-na-co-tesit#83'),
  array('Užívej si svou retardaci a primitivismus.'."\n".
'							--Petr Tomeš'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/ptomes/2009/5/je-wikipedie-duveryhodna-a-vyplati-se-do-ni-prispivat#482'),
  array('Další 32bit šmejďárna...'."\n".
'							--Jardík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/recenze/adobe-air-flash-a-ajax-na-desktopu#1'),
  array('Vidíte taky ty hnusný nekvalitní schodovitý přechody?'."\n".
'							--Jardík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/desktopy/jardik-20091008'),
  array('Logo ubuntu vytejká z panelu.'."\n".
'							--Jardík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/desktopy/xkucf03-20100516#1'),
  array('Akorát si v jednom videu na YuTube někdo stěžoval, že mu při používání tohoto mikrofonu'."\n".
'nestojí ve vzpřímené poloze (mikrofon).'."\n".
'							--jirkaqwe'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/poradna/hardware/show/315548#8'),
  array('A vida, echo z žumpy.'."\n".
'							--podlesh'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/doli/2009/5/miting-cssd-na-andelu#584'),
  array('Wokna mnohým lidem vyhovujou víc. Ovšem ne proto, že by byly lepší, ale proto, že tito'."\n".
'uživatelé jsou horší a platí svůj k svému ;)'."\n".
'							--Ash'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/ankety/microsoft-codeplex/diskuse#33'),
  array('AltOS: Bah! Az budou dlouhe zimni vecery, tak bych snad uz opravdu mohl "vytvorit" tu novou'."\n".
'distribuci Gambrinux...'."\n".
'Marek Stopka: Chtěl si říct Gambribuntu, ne?'."\n".
'AltOS: Ne, chtel jsem rici openGAMBRINUSE.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/puppylinux/2008/9/gnu-linux-vs-pivo#10'),
  array('S platností do konce roku budu vzorným křesťanem, nebudu číst Dawkinse, vzývat Cthulhu'."\n".
'a přestanu zabíjet koťatka.'."\n".
'							--kyknos'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/quid_novi/2009/12/prechazim-na-krestanstvi'),
  array('Nemůžete publikovat v minulosti!'."\n".
'							--abclinuxu.cz'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Untitled/2010/10/kernel-modul-kernel-ultras/diskuse#57'),
  array('Já myslel že seznamka už tady dávno je - vždyť je tady všude odkaz "Sbalit" :-O'."\n".
'							--podlesh'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/ze_zivota/2005/11/abcseznamka-ze-by-feature-request-.o#35'),
  array('Pokud jsi to vyčetl z hvězd, možná by stálo za to vyčistit si dalekohled.'."\n".
'							--trekker.dk'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/engineering/2009/3/nove-blogy-na-linuxsoftu/diskuse#33'),
  array('Windows jsou jako hamburger. Drahé, zbytečné, ale kupuje ho většina lidí.'."\n".
'							--Sten (anonym)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/linuxove-distribuce-prirovnany-k-jidlu#19'),
  array('MacOS X je jako kaviár. Extrémně drahý, chutná divně a lidé, co na něj mají, se jím rádi'."\n".
'chlubí.'."\n".
'							--Sten (anonym)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/linuxove-distribuce-prirovnany-k-jidlu#19'),
  array('Měříme si s kamarády uptime a pak si je ve škole porovnáváme, kdo ho má delší.'."\n".
'							--Jenda'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Untitled/2010/10/kernel-modul-kernel-ultras/diskuse#63'),
  array('Z Van Helsinga bys měl snad už vědět, že Praha a Budapešť jsou dvě jména pro totéž.'."\n".
'							--Nicky 726'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/itckar/2010/10/microsoft-vs.-skoda-120/diskuse#39'),
  array('Kazdopadne nema zmysel riesit, preco sa z francuzkej skodovky v madarsku dymi z predu v reklame na'."\n".
'shitosofti telefon :-)'."\n".
'							--msk'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/itckar/2010/10/microsoft-vs.-skoda-120/diskuse#21'),
  array('Je tu někdo z USA? Nechcete si patentovat "Patentování dlouhodobě a obecně používané'."\n".
'technologie za účelem získání výhodné právní pozice" ?'."\n".
'							--Jakub Lucký'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/kodovani-videa-na-gpu-patentovano/diskuse#13'),
  array('Držte svůj e-penis stále největší'."\n".
'							--Jakub Lucký'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Untitled/2010/10/kernel-modul-kernel-ultras/diskuse#61'),
  array('V (anonym): Obhospodarovat Arch je ako spat s vlastnou zenou - nenadchne, ale postaci...'."\n".
'Karel Benák: Dovoluju si nesouhlasit, jsem ženatý 5 let a jsem stále nadšený :-)'."\n".
'kyytaM: Z Archu, ci zo zeny?'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/dw/2010/10/novy-ubuntu-font-je-fajn/diskuse#22'),
  array('Jardík: Řetězce musí bít zarovnané vpravo.'."\n".
'tsLnox: A sakra. Jdu se zarovnat vlevo, nerad bych dostal řetězcem.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/jarda_bloguje/2010/11/gcc-umi-assembler-lepe-nez-ja#114'),
  array('Zprávička: Text ACTA byl vyjednán'."\n".
'heh: vzhuru na barikády....'."\n".
'Piškot: Co si to nejdříve přečíst ?'."\n".
'JS: Prectes si to na barikade. :-)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/text-acta-byl-vyjednan#5'),
  array('Zprávička: Francouzská policie přechází na Ubuntu'."\n".
'heh: Po dlouhé době jedna smysluplná zprávička obsahující slovo "ubuntu".'."\n".
'Semo: To zas Ubuntu krivdis. Ale je to po dlhej dobe jedna zmysluplna spravicka obsahujuca slovo'."\n".
'"francuzska".'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/francouzska-policie-prechazi-na-ubuntu/diskuse#4'),
  array('Dalibor Smolík: Když mi bylo 14 let, měli lékaři u mě podezření na lepru. Vážně, Dálný'."\n".
'Východ .. naštěstí planý poplach.'."\n".
'jozka: Asi bys byl jediny ctrnactilety, ktery by se neradoval z toho, ze mu neco odpadne...'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/diakritika-v-.cz-domenach-opet-odmitnuta#34'),
  array('Marcela: Co jste to zas vytvrořil, brouku? Nechcete taky někdy zprznit sám sebe? :-)'."\n".
'Bedňa: Treba priložiť prst na klitoris a použíť rýchle pohyby. Hovorí sa tomu stimulácia'."\n".
'nervových zakončení :-)'."\n".
'Amigapower: :-D  Já bych toho Paní (Slečnu???????????? Jak to vlastně je???????????) Marcelu'."\n".
'třeba i dobrovolně ušetřil ;-)'."\n".
'Bedňa: To ja bysom som si tu stimuláciu minimálne rád pozrel :-)'."\n".
'Amigapower: 10€'."\n".
'Bedňa: To beru'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2011/1/comix-kernel-ultras-0019/diskuse#14'),
  array('Honz: K čemu je na ploše nějaká cizí pipka...?'."\n".
'vain: No přece si tam nebudeš dávat tu vlastní, kterou vidíš taky každý den ;-)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/desktopy/drobek1015-20110128#11'),
  array('Hrabě Nikolič: Jak je to s tou rybou? <o))<'."\n".
'Mti.: Ryba smrdi od hlavy?'."\n".
'mirec: Ryba smrdí od ropy.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/komiks-xkcd-857-archimedes/diskuse#51'),
  array('xurfa: Klidek, to jen IPv6 fanatici vytvareji paniku, aby donutili vsechny ostatni prejit na ten'."\n".
'       jejich nedodelanej zmetek...'."\n".
'kip: Proč lozit do záchranných člunů, když orchestr pořád hraje, že?'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/v-regionu-asie-pacific-dojdou-v-dubnu-ipv4-adresy/diskuse#10'),
  array('Ale tohle je portál o Linuxu - lidi se tedy v diskuzi pravděpodobně budou chtít bavit o něm.'."\n".
'Kdyby lidé chtěli řešit politiku, půjdou jinam.'."\n".
'							--SPM'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/plastique/2010/10/liberix-ukazal-skolakum-ubuntu/diskuse#101'),
  array('Nakonec jsem rád, že se tu konkrétně tahle zprávička objevila, protože je zajímavá'."\n".
'narozdíl od zpráviček, že zítra, pozítří a včera výjde třetí alpha verze Ubuntu Horny Heron.'."\n".
'							--Neel'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/ubuntu-prestane-pouzivat-x.org/diskuse#82'),
  array('SP k Windows prý mají přinést volbu Disable DDOS, kterou když uživatel zaškrtne, tak bude'."\n".
'chráněn. Zkusím zapátrat na Slunečnici jestli tam na to není už nějaká utilitka.'."\n".
'							--Xerces (anonym)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/jak-se-vyporadat-s-ddos/diskuse#2'),
  array('Chtělo by to nějaké prášky proti lenosti.'."\n".
'							--xkucf03'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/jezkova_nora/2010/12/zda-se-mi-to/diskuse#39'),
  array('To já měl zas "Ha! Láva fárá". Pomůcka do Německy s úsměvem pro časování'."\n".
'nepravidelných sloves. Funguje asi z 85 %, což bylo vhledem k hranici testu 50 %, zcela'."\n".
'dostačující.'."\n".
'							--Voty'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/komiks-xkcd-809-los-alamos/diskuse#37'),
  array('Já to začal psát do HTML dokumentů:'."\n".
'  <meta name="generator" content="Zmagnetizovana jehla, osciloskop, pevna ruka a dokumentace ext3 :-)">'."\n".
'							--Jenda'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/komiks-xkcd-378-opravdovi-programatori/diskuse#3'),
  array('Troll krmí trolla. Tohle jsem nikdy nepochopil jak může fungovat. To je jako když zloděje'."\n".
'okrade zloděj. Nebo jako když markeťák naletí na reklamu.'."\n".
'							--Grunt'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/nokia-a-microsoft-zahajuji-spolupraci/diskuse#33'),
  array('už sem Android měl v prackách na mašince od THC'."\n".
'							--Migilenik'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/odi_et_amo/2011/2/pohreb-pro-nokia-a-meego-...-r.i.p/diskuse#20'),
  array('Hurdisky jsou asi média s Hurdem.'."\n".
'							--Jenda'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Untitled/2011/2/vize-verbalniho-computingu/diskuse#14'),
  array('Dobrý pant se hmatem nepozná. Pozná se ale olizem, musí studit.'."\n".
'							--frdrx'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/reklamace/2010/7/prosba-o-radu#50'),
  array('Mluvíte jako zapšklý dědek co závidí JJ živelnost, nadání a sex-appeal.'."\n".
'							--Marcela'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Strider_BSD_koutek/2010/8/napred-zabava-a-az-potom-prace/diskuse#400'),
  array('Zakaznici SONY nepotrebuji sex. Uz z nima vymrdala SONY.'."\n".
'							--belisarivs'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/sony-ma-pravo-ziskat-informace-o-uzivatelich-geohot.com/diskuse#14'),
  array('Když může měsíc způsobovat menstruaci, proč by nemohl způsobit zemětřesení? :-)'."\n".
'By mě zajímalo, co z toho působí větší škody.'."\n".
'							--frdrx'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Annals_of_Taurelador/2011/3/mesic-a-zemetreseni/diskuse#20'),
  array('to je zenska pivo a mliko :-D'."\n".
'							--kotyz'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/kotyzblog/2010/12/alkehol-ultras-comix-remix-by-kotyz#3'),
  array('$ TIME=12PM autoconf --with-knife --with-bible --sacrifice-dog'."\n".
'							--Kyosuke'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/programovani/cmake-zjednodus-si-zivot#3'),
  array('Pritelkyne ukladejte do tmp. Nikdy do home!'."\n".
'							--Dag'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/instalace_vmwaru/2006/3/14/124648#8'),
  array('Nemohu nevzpomenout onen pruzkum, ktery prisel na to, ze zhruba polovina mladych lidi vidi svou'."\n".
'situaci optimisticky. Druha polovina nema na drogy penize.'."\n".
'							--jozka'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/martinek/2011/4/ziji-v-krasne-dobe/diskuse#34'),
  array('Donutili jste mne podivat se do analu :-)'."\n".
'							--jozka'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/merlins/2011/4/ceny-benzinu/diskuse#145'),
  array('asociál: člověk s vlastním názorem, jedinec nepodléhající tlaku davové psychologie,'."\n".
'osobnost mimo úředně schválené sociální kategorie.'."\n".
'							--rADOn'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/bloK/2011/3/joke-of-the-day/diskuse#5'),
  array('A behem toho se dostavate do situaci kdy musite dokazovat python skill pred slecnou'."\n".
'ktera ma problemy s formatovanim textu ve wordu a jedine co poradne umi '."\n".
'je zahekat rediteli v posteli a rozhoduje o vasi budoucnosti.'."\n".
'(to jsem ji asi nemel rikat a mozna bych to misto dostal... neunesla pravdu)'."\n".
'							--P.P. (anonym)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/jarda_bloguje/2011/3/davky/diskuse#33'),
  array('A mě se vybavila jedna chyba, která se mi objevila nedávno:'."\n".
'Exception ESynaSerError in module bmrjd at 08058AC9.'."\n".
'Communication Error: SynaSer error: 5.'."\n".
'							--Jiří Lisický'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Linuxacka/2011/3/komiks-wili-kdyby-windows-byly-lide/diskuse#37'),
  array('oh no, my dear, I\' speaking english, but you englis is from google, isn\'t?'."\n".
'							--Jan Jílek'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Strider_BSD_koutek/2011/3/slusne-jsou-ze-vsech-nejlepsi/diskuse#111'),
  array('Mercuriuz: akorát bych nezkoušel zabavit manželku, to by mohl dostat tak akorát dárkovej koš :D'."\n".
'Sten: A proč ne? „Vydej mi heslo k WiFi, jinak ti vrátím manželku!“'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/komiks-xkcd-416-horlive-automaticke-nastaveni/diskuse#7'),
  array('Senior Database Programmer: Keď vyrazí ten vedľa mna v susednom pruhu tak je jasné'."\n".
'	že asi máme zelenú preto kuknem vtedy na semafor a rozjíždim se.'."\n".
'Jenda: Deadlock: blbý je, když se sejdou dva takovíhle vedle sebe :)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/leos/2011/3/kdy-radite-rychlost/diskuse#196'),
  array('Já jsem párkrát někomu udělal tu věc, že jsem našel wallpaper, udělal kopii,'."\n".
'vložil na něj obrázek složky s názvem "H0rse.Porn.XXX.Bestiality.HardC0rE"'."\n".
'a ten upravený obrázek pak dal jako wallpaper...'."\n".
'							--Jakub Lucký'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/ankety/zamykani-obrazovky/diskuse#47'),
  array('Tvrdis, ze pocitac (hw) bez Windows je viac hodnotny ako pocitac s Windows'."\n".
'a preto za neho bude vyrobca pytat viac. No, nieco na tom bude :)'."\n".
'							--Semo'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/ffii-zada-o-pomoc-pri-boji-proti-bundlovani-windows/diskuse#18'),
  array('Eso Rimmer: Trochu offtopic, ale dnes jsem přemýšlel, jaký je ideální počet členů parlamentu.'."\n".
'	Co myslíte? Osobně bych zrušil senát a parlament zmenšil tak na třetinu.'."\n".
'PepaSFI: navrhuju vrstvovou metodu. Vrstva politiků, vrstva hlíny, vrstva politiků, vrstva hlíny....'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Strider_BSD_koutek/2011/4/opilci-a-politici/diskuse#14'),
  array('Cloud je buzzword zmrdspeaku.'."\n".
'							--Grunt'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/PhaX_blog/2011/4/nemam-rad-slovo-cloud/diskuse#6'),
  array('Asi nejkratsi mozny zapis, ale vykouzlil mi usmev na tvari.'."\n".
'** WARNING: found gd.h header file in /usr/include/gd.h, but it is expected at /usr/include/gd.h.'."\n".
'This may cause compile errors! **'."\n".
'							--Zdeněk Štěpánek'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/uz_mam_taky_blog/2006/6/perl-me-pobavil'),
  array('motyq: v originalu se pise ze nastavila teplotu na 450st, jednak bych chtel videt troubu'."\n".
'	ktera da 450stC (i kdyz v emerice maj treba nejaky specialni),'."\n".
'	pak ten recept kterej takovou teplotu chce :D'."\n".
'Atom321: V Americe nemají speciální trouby, ale speciální stupnici teploty.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/palm-pixi-prezil-upeceni-v-troube#12'),
  array('Gonic (blog): Na rychlé lajně - 3 měsíce'."\n".
'	Pokusím se tu nějak slušně napsat zkušenosti s používáním internetu při rychlosti 100/100 Mbit/s.'."\n".
'Amigapower: čekal sem metanfetaminovej zápisek :D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/moje/2010/3/na-rychle-lajne-3-mesice#40'),
  array('Blog: Proč přeběhlo kuře přes cestu?'."\n".
''."\n".
'"David Watzke: Kuřata jdou... A co Bulánci, jedou?!'."\n".
'Darek ADIO Zabdyr: To jsou na mně novinka. Kuřata byla chodit přes chodníka. Napíšu o tom do E-magazin.'."\n".
'	Shánila tam nový redaktor. A NEJSEM NĚMEC, NEPTALA SE!!!!!'."\n".
'JK: No jo, kureci urvanci, co se dalo cekat... Fakt uz me nebavi poslouchat ty blby kecy od nich.'."\n".
'	Ale kurata za to nemuzou, to jejich uzivatele. Stejne je to moda,'."\n".
'	ktera pomine, a vsichni se vrati zpet ke korenum - k DEBIANu.'."\n".
'Vladimir USAMA Zima: curaci zasrany kurva chci aby tam ty kurata nesli pres tu silnice kdyz rykam '."\n".
'	ze nechci tak tim mislim ze me to sere kdyz to delaj do pici jdu raci omrdat svou starou.........'."\n".
'Jan Strider Jílek: Vrátil jsem se domů a ulehl ke své mladé přítelkyni. Ukazoval jsem jí fotografie'."\n".
'	mých předchozích kuřat, ale moc to na ni nezapůsobilo. Asi stárnu.'."\n".
'	Tak jsem si alespoň překompiloval lynx. Pokrok nezastavíš.'."\n".
'Petr Tomeš: Jste zcela nekompetentní sem o kuřatech psát. Nejste novinář. Trpíte navíc nedostatkem'."\n".
'	intelektu a argumentů. Mohl byste prosím alespoň uvést zdroj vašich zpráv? Já se domnívám, že nikoli.'."\n".
'	Prostě nám tady lžete. Já si vás řadím mezi další "šílené novináře". Takových je tu konec konců dost.'."\n".
'	Vlastně, když nepočítám sebe, tak všichni.'."\n".
'OK1AS: + 1"'."\n".
'							--freshmouse'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Vencour/2007/6/vidim-den-kdy-kurata-pres-cestu-budou-svobodne-chodit#13'),
  array('kotyz: kuny? a nechybi vam tam nahodou jedno pismenko? ja vim ze nechybi,'."\n".
'       ale neodolal sem pokuseni trosku si rejpnout ... :-D'."\n".
'Marcela: To jsem přesně čekala. Kuny, kotyzi. Kuničky.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Strider_BSD_koutek/2010/6/feministky-do-pekla/diskuse#157'),
  array('Blog: Zaujala ma moznost mojej banky vytvorit si vlastny namet kredit karty '."\n".
'  a ten Vam banka vytlaci na vasu bankomatovu kartu (...) Mimochodom nejake navrhy?'."\n".
''."\n".
'Jardík: Foto svého penisu ...'."\n".
'xxxs: myslim, ze by si sa neovladol a porusil bod 11.'."\n".
'      obrázky zjavne upravované počítačovými programami, najmä fotomontáže.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/home_feco_blog/2010/11/iluzia-slobody#6'),
  array('Amigapower: Cadillac Fleetwood 1994, to je úspornej motor, jde to najít na netu ;-)'."\n".
'Bedňa: Cadillac je známy svojimi úspornými motormi :-)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2011/5/mundikat-show-rijnhal-arnhem-nl/diskuse#27'),
  array('Lord Vetinari: Neda mi, ake diskove pole abclinuxu pouziva?'."\n".
'Amigapower: O ploše 12 hektarů, je hned vedle mého konopného a Kotyzova bramborového pole.'."\n".
'	    Na podzim vždycky Doli sedne na kombajn a sklízí disky. :-D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/omluva-za-vypadek#18'),
  array('Jenda: Ano, ten zanedbatelný podíl IPv6 skutečně nasere.'."\n".
'Grunt: To je první čeho si všimneš? Co vyšetření?'."\n".
'Jenda: Myslíš ten test na IQ? Díky Bohu negativní.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/status_quo/2011/5/ceska-televize-pohrbila-online-vysilani/diskuse#44'),
  array('Zprávička: Ovladač pro vnořené X servery'."\n".
'Joseph (anonym): Yo dowg, i heard you like xserver so we put xserver into your xserver.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/ovladac-pro-vnorene-x-servery/diskuse#7'),
  array('Také jsem nevěděl, co jsou to "becky" :-) To mi připomíná kamaráda, který mi kdysi'."\n".
'poslal SMS od Jadranu a chtěl naznačit, jak je vzduch provoněný mořskou vodou,'."\n".
'omezil se na strohé "VZDUCH JE CITIT MOREM"'."\n".
'							--Dalibor Smolík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/puppylinux/2011/5/delate-becky/diskuse#12'),
  array('Vis, kde je hranice stari? Tehdy kdyz neberes po dvou schody, ale prasky.'."\n".
'							--jozka'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/puppylinux/2011/5/delate-becky/diskuse#57'),
  array('Hue: 10°C? Máš PC na balkoně?'."\n".
'luta: weatherwidget'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/desktopy/examon-20110515/diskuse#3'),
  array('Blogy: Jaké to je být vychováván stejnopohlavním párem? --Petr Tomeš'."\n".
'xkcd česky: Nerd holky'."\n".
'SPM: Jak jsem po ránu rozespalej, tak jsem čet "Nerad holky"... a už jsem si pomyslel,'."\n".
'vzhledem k událostem posledních dnů, jakej to bude tady flame :)))'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/komiks-xkcd-67-nerd-holky/diskuse#4'),
  array('Buď ukažte, kde jsem se tam provinil, nebo se mi omluvte, že mám skutečně pravdu a diskutovat se zde nedá.'."\n".
'							--Petr Tomeš'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/ptomes/2011/5/slusnou-diskusi-nelze-vest-v-zumpe/diskuse#141'),
  array('Diskuse o průniku na server:'."\n".
'pc2005: Heh tak mě napadlo, že vlastně opravdu úspěšný průnik bych nikdy nezjistil.'."\n".
'Dalibor Smolík: Hlavně, aby ho zaznamenala přítelkyně :D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/ankety/policie-napadeni-serveru#12'),
  array('Jinak nechápu proč se zas vymýšlí kolo když ImageMagick je to s námi již cca. 100 let.'."\n".
'							--Grunt'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/itckar/2011/5/hq.pixelmap-vylepseny-filter-saturacie-bez-skreslenia/diskuse#15'),
  array('Prohodil bych te zasklenym balkonem ...'."\n".
'							--dad'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/kacirstvi/2011/5/pomahame-a-chranime.-za-vsechny-prachy/diskuse#18'),
  array('Já zas v pátek odcházim na mateřskou.'."\n".
'							--Amigapower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Supi_hnizdo/2011/5/csob-ve-firefoxu-na-linuxu-a-adopce-deti-homosexualy/diskuse#54'),
  array('Jílek, latinsky Lolium, je rod travnatých bylin z čeledi Lipnicovitých.'."\n".
'V České republice můžeme vidět v současnosti jen 2 druhy z rodu jílek.'."\n".
'Velmi hojný je jílek vytrvalý (Lolium perenne), který obsazuje krátkostébelné louky, často sešlapované.'."\n".
'Jílek mnohokvětý (Lolium multiflorum) bývá robustnější a má osiny.'."\n".
'Je to druh hojně přisévaný do kulturních produkčních luk.'."\n".
'							--Miloslav Ponkrác'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/systemakuv_blog/2011/5/davam-manazerskemu-kapitalismu-17-let-spis-min/diskuse#205'),
  array('Stable release msys je na Vistě x64 absolutně nestabilní a tak jsem byl nucen stáhnout nestabilní, která byla stabilní :-)'."\n".
'							--Jardík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/jarda_bloguje/2008/9/gtkmm-pro-windows-x64'),
  array('kotyz: Jo, to mě taky vždycky fascinovalo, jak sou všichni proti Temelínu, ale Dukovany nikomu nevadí.'."\n".
'Heron: Lidem to ale nevadí, každý tam doslova září :-D'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/no_comment/2011/6/dzin-vypusteny-z-lahve-aneb-co-ted/diskuse#27'),
  array('Proč to nevzít zgruntu'."\n".
'							--Grunt'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/hlava22/2011/6/hrajeme-si-na-odborniky-nebo-jsme-pokrytci/diskuse#40'),
  array('Optimista se uci anglicky. Pesimista se uci cinsky. Realista se uci strilet.'."\n".
'							--dementni.lojzik'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/hlava22/2011/6/hrajeme-si-na-odborniky-nebo-jsme-pokrytci/diskuse#47'),
  array('Michal2: Nejsem sice sitar ale nevidim na prvni pohled prekazku v tom, udelat v ipv6 NAT.'."\n".
'	 Teda kdyby nekdo mermomoci takovou volovinu delat chtel.'."\n".
'SPM: Překážka je v tom, že by tu implementaci napřed musel někdo napsat,'."\n".
'     což díkybohu takyadmini, co ho tak potřebují, nezvládnou...'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/vejsplechty/2011/6/je-skutecne-maskarada-nat-tak-zbytecna-a-spatna/diskuse#28'),
  array('Navíc nemám pocit, že psaní síťových věcí by byl vrchol obtížnosti v programování.'."\n".
'Patří to spíše k těm jednodušším programátorským úlohám.'."\n".
'							--Miloslav Ponkrác '."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/vejsplechty/2011/6/je-skutecne-maskarada-nat-tak-zbytecna-a-spatna/diskuse#44'),
  array('Mě se naopak při stávce pracuje lépe než kdy jindy,'."\n".
'protože kvůli ní přítelkyně vyrazila do práce už včera večer.'."\n".
'							--pavlix'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/jenda/2011/6/tak-jak-zvladate-stavku-hd/diskuse#32'),
  array('MHD ma za drahý peniaz dopraví nepohodlným spôsobom v čase, ktorý sa mi nehodí,'."\n".
'z miesta, kde nie som, na miesto, kam sa nechcem dostať.'."\n".
'							--rastos'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/rocfdebian/2011/6/vyhodnost-mhd-oproti-autu/diskuse#145'),
  array('a co tak napriklad vyskusat vyssie cisla v IP, az sa mi nechce verit'."\n".
'ze to doteraz nikdo nevyskusal,napr. ip by bola 684.953.700.**'."\n".
'							--anonym'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/ankety/svetovy-den-ipv6/diskuse#37'),
  array('Blogpost o kódovém vysacím zámku:'."\n".
'Mercuriuz: jů, to je jeden z těch kterej mám otevřenej do dvou minut...nekecám ;)'."\n".
'Jenda: Se znalostí kódu nebo bez?'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Tomik/2011/6/vnitrnosti-kodoveho-zamku/diskuse#17'),
  array('> 1. V jakém věku se pozná, jaká je orientace člověka?'."\n".
'	politická? mně je 34 a dál se vyvíjí...'."\n".
'> 2. Jakým způsobem se bezpečně pozná, jaká je ta orientace ?'."\n".
'	u voleb'."\n".
'> 3. Prý se pro diagnózu používá nějaká falometrie ?'."\n".
'	Ano, po volbách nemáš peníze na benzín, tak jezdíš metrem jako falus'."\n".
'> 4. Která orientace je správná, ta většinová nebo i ta menšinová ?'."\n".
'	rozhodně jsou všechny stejně špatný'."\n".
'> 5. Když se prokáže menšinová orientace u člověka, je to nemoc ?'."\n".
'	ne, trestný čin'."\n".
'> 6. Co když někoho zajímají obě možnosti, je to nemoc ?'."\n".
'	ano, schýza'."\n".
'> 7. Má se menšinová orientace veřejně přiznat nebo je lepší to tajit ?'."\n".
'	pokud nechceš dostat třeba podporu a propagaci... tak ji raději taj'."\n".
'> 8. Je to špatně, když člověka nezajímá ani jedna ani druhá možnost ?'."\n".
'	ne, je to fajn'."\n".
'							--Amigapower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/bigblog/2011/6/sedm-dulezitych-zivotnich-otazek/diskuse#2'),
  array('třeba ted zmizí reklamy na super čaje z "lung-mig-švink - o půlnoci ve středu kvetoucí '."\n".
'tajemné čípkové růže" léčící všechno od řídkého spermatu po upadlou ruku'."\n".
'a na bylinkových čajích se místo "léčí nachlazení" bude psát "může pomoci při léčbě nachlazení".'."\n".
'							--marek_hb'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Max_Devaine/2011/5/eu-chce-zakazat-pestovani-hermanku-dobromyslu-aj.-bylin#7'),
  array('Málem jsem poprskal televizi, když jsem se dozvěděl, že Bitcoin je nebezpečný,'."\n".
'protože nad ním vlády nemají kontrolu a nemohou tak zablokovat účty teroristům, íráncům a korejcům.'."\n".
'							--Petr Bravenec'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/hodnota-bitcoinu-prekrocila-100-mil.-usd/diskuse#46'),
  array('masožravá palma: Pry je v tom nejaka elektronika, a vydrzi to neomezeny pocet zasahu [bleskem].'."\n".
'		 Jak rikam, ochrana nabozenskeho charakteru.'."\n".
'Amigapower: Leda že by to bylo varle z terminátora :D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/tar_zxpf/2011/6/anketa-vypinat-pri-burke-pocitac#12'),
  array('Miloslav Ponkrác: NAT v IPv6 prostě bude.'."\n".
'trekker.dk: Jsi si tím jistý, pane astrologu? Aby to nebylo jako posledně, když se ti na čočku vysrala moucha.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/vejsplechty/2011/6/je-skutecne-maskarada-nat-tak-zbytecna-a-spatna/diskuse#49'),
  array('Je třeba dbát na dostatečném množství krve, aby jí mozek měl dost i poté, co se jí část odleje někam jinam :)'."\n".
'							--SPM'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Newkilleruv_Blog/2011/6/jaka-je-vase-sexualni-orientace/diskuse#200'),
  array('Blog: Když se partnerka pana K. dozvěděla, že je nezaměstnaný, vyhodila ho z bytu, který jí patří.'."\n".
'Salamek: uh co to je za mrchu?'."\n".
'belisarivs: Na kazdou svini se vari voda.'."\n".
'frdrx: Jo? Na tu mojí taky? :)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/txt/2011/6/bloger-spachal-pokus-o-sebevrazdu/diskuse#37'),
  array('Ač nejsem příznivcem přílišných vulgarit, musím smutně konstatovat, že jsem zase vyhrál hovno!'."\n".
'							--(neznámý autor - smazaný profil)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/ruzne/losovani-o-ceny#51'),
  array('anonym: A ten fotograf tam má ke všemu erotické obrázky.'."\n".
'xkucf03: To je skandální, hned se jdu podívat :D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/bigblog/2011/6/psat-do-blogu-zde-nebo-na-zive.cz/diskuse#46'),
  array('Anketa: Jaký máte vztah k matematice?'."\n".
'JeanVEGA: Mozno by aj bol kladny, keby ma ju neucila ta zubata opica... :D'."\n".
'neznámý autor: v nazvu zubata opica ti zrejme prebejva jedno o'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/ankety/jaky-mate-vztah-k-matematice#26'),
  array('Policajti provádějí spálení zesnulého hozením do kopřiv.'."\n".
'							--Dalibor Smolík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Linuxacka/2011/4/komiks-wili-zahradnice#150'),
  array('Autorem je dívka opačného pohlaví.'."\n".
'							--anonym'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Linuxacka/2011/4/komiks-wili-zahradnice#8'),
  array('Já jsem kdysi používal MS Access, pak jsem na to bral nějaké prášky a přešlo to.'."\n".
'							--Dalibor Smolík'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/miriam/2011/6/proc-me-zdejsi-uzivatele-nemaji-radi/diskuse#141'),
  array('pavlix: Ty máš nějaké omezení v oblasti plodnosti?'."\n".
'Amigapower: ...má tak velký péro, že se do žádný nevejde :D'."\n".
'davkol: To už bych byl (a) v nemocnici, nebo (b) v jižní Kalifornii.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/miriam/2011/6/proc-me-zdejsi-uzivatele-nemaji-radi/diskuse#333'),
  array('Vono porád smartfouny smartfouny.. Já si to kupovat nebudu, počkam tři roky a pak se to bude přidávat do kindrvajec.'."\n".
'							--jeleniste'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/xkucf03/2011/7/proc-lzes-obchodniku/diskuse#123'),
  array('Na ženský sem ještě mladý. Ještě sem prostě nedozrál. Nejdřív VŠ, potom se uvidí, říkají i naši.'."\n".
'							--Petr Kratochvíl'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/mujlinux/2011/7/zvyste-svoji-inteligenci-prostrednitvim-softwaru-pro-linux/diskuse#78'),
  array('Co Čech, to: "Já nic já muzikant."'."\n".
'							--belisarivs'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/mujlinux/2011/7/zvyste-svoji-inteligenci-prostrednitvim-softwaru-pro-linux/diskuse#200'),
  array('Dneska máme v našem centru, ukrytém hluboko pod Himálajemi a propojeném chodbami do všech světových bank,'."\n".
'parlamentů a zpravodajských centrál trochu nervozní atmosféru. Hlavnímu rabínovi spadla kippa'."\n".
'do necek s cementem velmistra Zednářů. Aštar Šeran postrádá dva milióny flotil vesmírných plavidel,'."\n".
'kope do zdi a řve: "Do piči". Rosenkruciánům někdo zalil růže travexem.'."\n".
'							--Dag'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Kuk/2009/1/z-deniku-hlavniho-spiklence'),
  array('Jojo, po takove homeopaticke Whisky se clovek vzdycky priserne opije,'."\n".
'ze si ani nepamatuje, co si z ni ta voda pamatovala :)'."\n".
'							--Gilhad'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/science/2011/7/ovladani-pocitace-myslenkou/diskuse#378'),
  array('Řekl bych, že pravdu má Jenda a dost brzo zakrní.'."\n".
'							--pc2005'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/science/2011/7/ovladani-pocitace-myslenkou/diskuse#931'),
  array('Pod blogem o směšné lokalizaci:'."\n".
'Petr: Líbí se mi to. Nebylo by ale hravější "erekce rozhraní eth0"? ale nevím co s down'."\n".
'houska: "rozhrani eth0 povadlo"'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/pyx/2011/7/boura-se-rozhrani#3'),
  array('Amigapower: ...ale teď mi nejede zvuk v youtube'."\n".
'vencour: Stáhnout přes dwhelper a kouknout v mplayeru?'."\n".
'Amigapower: Když se chci vychcat, vyáhnu ptáka a chčiju, nechci to dělat jako ženský,'."\n".
'	položit prkýnko, povolit pásek, sundat kalhoty, sundat spoďáry, sednout si, '."\n".
'	pak teprve chcát a ještě si k tomu utírat papírem ptáka... ;-)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Untitled/2010/4/fsck.ext3-je-nedeterministicky/diskuse#38'),
  array('Kolibáč na záchodě:'."\n".
' (>_<)'."\n".
' (°_°)'."\n".
' (O_O)'."\n".
' (O_o)'."\n".
' (^_^)'."\n".
'							--Jenda'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/mirecove_dristy/2011/8/tvorba-webovych-stranok-vs.-programovanie/diskuse#47'),
  array('Blog: žádost o překlad do švédštiny'."\n".
'xxxs: http://translate.google.com/#sv|pl|'."\n".
'Amigapower: Můj google mluvit švédské jako číňan v americká film :D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2011/8/neumyte-negdo-fyncky#12'),
  array('Bůh není zdaleka takový blb, jak si ho naprostá většina křesťanů představuje.'."\n".
'							--pavlix'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/science/2011/7/ovladani-pocitace-myslenkou/diskuse#1430'),
  array('Prídite do USA, vaše dáta tam už sú.'."\n".
'							--Bedňa'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/vladni-instituce-usa-ziskaly-pristup-k-evr.-datum#4'),
  array('HW novinky: až 100W odběr z USB konektoru'."\n".
'miki.lbc: Takže ti co mají USB ohřívač hrnku, si teď můžou koupit USB kávovar :))'."\n".
'AsciiWolf: Jo a ti co mají USB vibrátor si teď budou moci koupit USB příklepovou sbíječku. :D'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/hw-novinky-az-100w-odber-z-usb-konektoru/diskuse#25'),
  array('Nikdy nikoho nepřesvědčuj k přechodu na Linux! Místo toho jdi příkladem - používej Linux,'."\n".
'zodpovídej případné otázky a pokud bude mít někdo zájem, zauč ho, pomoz mu.'."\n".
'Ale nikdy, opravdu nikdy, nikoho nepřesvědčuj, násilně či nenásilně.'."\n".
'Jinak budeš přesvědčeným okolím považován za příčinu jakéhokoliv problému,'."\n".
'bude s tebou nakládáno jako s neplacenou podporou.'."\n".
'							--Shadow'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/-20-let-od-prvniho-oznameni-vyvoje-linuxu/diskuse#43'),
  array('frdrx: Opakuju, teisty jsou všichni kdo věří v boha a ateisté jsou všichni ostatní.'."\n".
'Dag: Kdepak, to je úplně naopak! Ateisté jsou ti, co nevěří v boha, teisté jsou všichni ostatní.'."\n".
'phr: Nemáte pravdu ani jeden. Ateisté pijou kafe, teisté čaj.'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Linux_nieje_jadro_ale_komunita/2011/8/pozriem-si-abicko-a-hned-prva-dva-desktopy-od-homosexualov/diskuse#342'),
  array('Makra v C jsou jako koření v kuchyni. Nakrájejte půl kila hovězího na plátky,'."\n".
'rozdrťte patnáct kuliček pepře a poduste to. Bude vám to chutnat.'."\n".
'Ale zkuste to v poměru 1:1 - půl kila hovězího a půl kila pepře...'."\n".
'chtěl bych vidět váš kyselý xicht ;-)'."\n".
'							--Petr Bravenec'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/trained_monkey/2011/9/z-javy-do-cplusplus/diskuse#102'),
  array('Jeden z uvedených patentů popisuje:'."\n".
'  Instrukce A -- převádí obsah registru A na 16bitové číslo a ukládá do registru C'."\n".
'  Instrukce B -- převádí obsah registru A na 32bitové číslo a ukládá do registru C'."\n".
'  ...'."\n".
'Krom toho, že podobná operace jsou primitiva, napadá mě — asi si patentuju sraní do mísy :D'."\n".
'Tedy pardon, uložení hmoty H do místa M. Jsem zvědavej, co budete vy ostatní dělat potom :)'."\n".
'							--misacek (anonym)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/via-zaluje-apple/diskuse#20'),
  array('Signaly a messages - zde mam pocit, ze ten signal-slot konzept je jakasi mantra intergalaktickeho programovani.'."\n".
'							--jkb (anonym)'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/flare/2011/11/wxwidgets-vs-qt/diskuse#9'),
  array('Jez do polosyta, pij do polopita a spi do poledne ;-)'."\n".
'							--kotyz'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/bystroushaak/2011/12/cestovani-v-casovych-pasmech/diskuse#40'),
  array('Blog: Jak v Mladé frontě (živě.cz) nepochopili OpenID'."\n".
'jozka: Jestli budes psat blog pokazde, pokud na lzive neco nepochopi, mas zadelano na peknej serial :-)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/pavlix/2011/11/jak-v-mlade-fronte-zive.cz-nepochopili-openid#3'),
  array('Woknař-anonym: Chtěl bych napsat, že výše se realizující Woknař si vypůjčil můj nick. Dále no comment.'."\n".
'Woknař-registrován: Hotovo, teď je to můj nick.'."\n".
'belisarivs: Vyborne -> Block'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Karl/2011/10/jadro-systemu-window/diskuse#73'),
  array('w4rr10r: To už je dost NSFW.'."\n".
'Amigapower: Co to je? Need for speed?'."\n".
'Anonym: NSFW - Need Speed For Windows'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2011/10/trika-kernel-ultras-damska-verze#8'),
  array('Pravda, zabít komára lze několika způsoby.'."\n".
'Proč si - kupříkladu - otloukat tlapku, když můžu použít protiletadlové dělo...'."\n".
'							--D.A.Tiger'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/zemrel-dennis-ritchie/diskuse#99'),
  array('> "Komunismus by mohl fungovat pouze v ideální společnosti s ideálními, uvědomělými a nesobeckými jedinci"'."\n".
'Také jsem si to kdysi myslel, ale pravda je ještě jednodušší,'."\n".
'v takovéto společnosti by dobře fungovalo jakékoliv zřízení.'."\n".
'							--bigBRAMBOR'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/kenyho_stesky/2011/11/zpetne-uz-se-nikdo-nepta/diskuse#2'),
  array('Zaslechli jsme, že i česká společnost Zentiva připravuje žalobu,'."\n".
'neboť prodávala tablety minimálně 20 let před Applem...'."\n".
'							--David Ježek'."\n".
''."\n".
'', 'http://www.diit.cz/clanek/via-zaluje-firmu-apple-chce-zakaz-prodeje-pristroju-iphone-a-ipad/38845/'),
  array('Anonym: A mě by zajímalo proč tady ještě tihle kokoti nemaj BAN???'."\n".
'Anonym: IMHO by bylo zajímavý porovnat graf návštěvnosti s grafem aktivit této vulgární sebranky.'."\n".
'Amigapower: Asi by ti vypadly koule nohavicema a do pytliku zapadly voči...'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/kotyzblog/2011/12/silvestr-s-kernel-ultras#60'),
  array('Mst. Spider: Koukam, ze to delaji v Cine - bude tam nejakej ten backdoorek jako bonus? :D'."\n".
'pasmen: Debilní diakritika... Čtvrt hodiny jsem hledal, co je Cine za vývojový prostředí,'."\n".
'	než jsem si všimnul, že to píšou v Číně...'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/longene-linux-binarne-kompatibilni-s-windows#4'),
  array('> Zprávička: Ovladač VirtualBoxu navržen na příznak TAINT_CRAP'."\n".
''."\n".
'Innotek -> SUN -> ORACLE'."\n".
'Dnes již tradiční cesta do prdele :D'."\n".
'							--heh'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/ovladac-virtualboxu-oznacen-priznakem-taint-crap#3'),
  array('Leda že by se uplatnila shoda podle smyslu. Například by se dalo psát "Rychlé šípy šukali po místnosti,"'."\n".
'protože to jsou samozřejmě kluci. V dotyčných románech je, pravda, použita shoda podle gramatického rodu,'."\n".
'takže "Rychlé šípy šukaly..."'."\n".
'							--Mandarinka'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/microsoft-a-suse-obnovily-smlouvu-o-interoperabilite#9'),
  array('Konstruktivní lenost. Lidé udělají vše pro to, aby nemuseli nic dělat.'."\n".
'							--Josef Kufner'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/veterina/2011/8/vetsina-studentu-jsou-ufnukani-lenosi/diskuse#82'),
  array('sabraq: To "jop" je překlep, nebo počeštěné světácké "yep"?'."\n".
'HFechs: Ani jedno, ani druhé. Je to "jo pičo" ;-P. Aspoň to tak chápem já a jeden známý Ostrávak ;-)'."\n".
'sabraq: Ach takp :-P'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/clanky/hw-novinky-az-100w-odber-z-usb-konektoru/diskuse#48'),
  array('Krokodýlí řeku může překonat jen Krokodýlí řeka 2! Delší o 25%, o 30% více akce,'."\n".
'o 60% horší scénář a o 100% větší rozpočet :D'."\n".
''."\n".
'A ovce to budou žrát ... ;)'."\n".
'							--kotyz'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/leos/2011/12/bilancovani/diskuse#315'),
  array('Takhle se alokuje:'."\n".
'(gdb) call malloc(100)'."\n".
'$1 = 14324840'."\n".
'Pak CTRL+C, CTRL+V'."\n".
'							--Grunt'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/firefox_bal/2012/1/ukazatele-a-jazyk-c/diskuse#184'),
  array('Snad mě nebudete kamenovat za off-topic zápisek, který nesouvisí ani s politikou,'."\n".
'ani s řízením automobilu, ani s amatérskou psychoterapií.'."\n".
'							--pavlix'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/pavlix/2012/1/programek-na-faktury'),
  array('Amigapower: neni tam popis...'."\n".
'Martin Petr: Jak to, že není? 1.Name 2.Email 3.Your website'."\n".
'Amigapower: Ale já tam mam jen prázdný vokýnka :D'."\n".
'otula: Tak si do nich prosím tě dej aspoň pelargonie ;)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/generalni-stavka-internetu/diskuse#40'),
  array('Marcela odchází z makrobiotického mejdanu, žaludek plný bršlice a pastyňáku.'."\n".
'Divná tíseň ji padá na srdce i střeva. V tom zahlédne hejno koček, kroužících nad střechami města.'."\n".
''."\n".
'"Vždyt já ho miluji!" Uvědomí si náhle prozřelá! Nedbaje že jsou tři ráno'."\n".
'(on je miláček stejně zhulenej to neva) běží, letí za svým Amigou!'."\n".
'Pozdě. Zapoměl nakrmit ráno kočky a ty se nakrmily Amigou. Ohryzané umírající tělo'."\n".
'se shoulí do klína Marcele a poslední vyznání lásky je i posledními slovy kočkomila.'."\n".
'Marcela se pak rozhodne opustit světský ruch a zbytek života stráví'."\n".
'v útulku pro kočky (tedy jako pracovnice, ne kočka).'."\n".
'							--Dag'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/BLB/2012/1/bojim-se-zmenit-znacku/diskuse#10'),
  array('"Poté co mi došlo, že nejsem genius, rozhodl jsem se zešílet."'."\n".
'							--Bystroushaak'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/bystroushaak/2011/11/paranoidni-teorie-hracu/diskuse#28'),
  array('život je paranormálny jav'."\n".
'							--whistleblower'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/Kuk/2012/1/-psi-zivot/diskuse#92'),
  array('Zprávička: HP otevřelo framework Enyo a zveřejnilo roadmapu pro celý webOS'."\n".
'Mandarinka: Super, už brzo se to bude dát sloučit s Tizenem :3'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/hp-otevrelo-framework-enyo-a-zverejnilo-roadmapu-pro-cely-webos/diskuse#3'),
  array('gtz: No vem si, že dnes bylo u nás přes den něco kolem -12°C a v tom počasí si hodně lidí nevylízá,'."\n".
'	natož aby někdo šel někam demonstrovat.'."\n".
'SPM: Já mám teda pocit, že většina lidí si nevylízá ani v plus dvaceti :)'."\n".
''."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/proc_dalsi_nazev/2012/2/protest-piratu-proti-acta/diskuse#68'),
  array('Dopustil ses argumentu „ad Tomešum“'."\n".
'							--pavlix'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/blog/merlins/2012/1/restituce-cirkvi-2012-nekonecny-pribeh/diskuse#377'),
  array('Když mají dva lidé jahody a jeden z nich je sní, tak ten druhý přijde zkrátka.'."\n".
'Pokud mají dva lidé knihu a oba si jí přečtou, tak vznikne škoda tím,'."\n".
'že místo jednoho vzdělaného člověka tu máme dva vzdělané lidi. To je ta škoda.'."\n".
'							--pakanek'."\n".
''."\n".
'', 'http://www.abclinuxu.cz/zpravicky/zakladatele-the-pirate-bay-odsouzeni#24'),
  array()
);
